#didn't need beautifulsoup fo this as this is running on JS and i just got the json file with the link
import requests
import smtplib
import os
from dotenv import load_dotenv
from email.message import EmailMessage
from email.utils import make_msgid

load_dotenv()

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

res = requests.get('https://remoteok.com/remote-python-jobs.json', headers=headers).json()
# req - envelope

report_body = "ARACHNET JOB REPORT: NEW PYTHON JOBS\n"
report_body += "="*40 + "\n\n"

# 2. Skip the first item (just metadata)
jobs = res[1:] 

# 3. Process the "Real" Intel
for job in jobs:
    title = job.get('position')
    tags = job.get('tags')
    company = job.get('company')
    url = job.get('url')
    salary = job.get('salary_min', "not given")
    location = job.get('location')
    posted_date = job.get('date')
    
    if "python" in tags:
        report_body +=  f"title: {title}\n"
        report_body += f"company: {company}\n"
        report_body += f"minimum salary: {salary}\n"
        report_body += f"location: {location}\n"
        report_body += f"oosted on: {posted_date}\n"
        report_body += f"link: {url}\n"
        report_body += f"{'-' * 30}\n"


msg = EmailMessage()
msg['Subject'] = f"Scout Report: {len(jobs[:10])} New Positions Found"
msg['From'] = os.getenv('EMAIL_USER')
msg['To'] = ('') # Send it to yourself 


# make_msgid() generates a unique, random "passport number" for your image (e.g., <12345@victus.local>).
image_cid = make_msgid()
#In the HTML, we set the source to cid:12345@victus.local. 
#This tells the email client: "Don't look for this on Google; look for the part of this email that has this ID.

# 2. Set the HTML content (referencing the CID) - content id
# Standard emails are "Plain Text." To use images and bold fonts,
# we use add_alternative. This creates a Multipart/Alternative message.
# It sends both a text version (for old phones/security) and an HTML version.
# The HTML version acts as the "frame" for our report.
msg.add_alternative(f"""
<html>
    <body style="font-family: Arial, sans-serif;">
        <h1 style="color: #2e6c80;">Arachnet Report Visual</h1>
        <p>Information you requested!:</p>
        
        <img src="cid:{image_cid[1:-1]}" style="max-width: 100%; height: auto;">
        
        <h3 style="border-bottom: 1px solid #ccc;">Scout Log:</h3>
        <pre style="background-color: #f4f4f4; padding: 10px;">{report_body}</pre>
        
        <p>Generated by <strong>Arachnet Intelligence</strong>.</p>
    </body>
</html>
""", subtype='html')

#Because the image is "related" to the HTML (it's part of the visual layout), we use .add_related().
with open("arach.jpg", 'rb') as img: #read binary
    #msg.get_payload()[0]: This reaches into the first "drawer" of your email (the HTML part) 
    #to attach the image directly to it, rather than just throwing it in the general "attachment" bin.
    msg.get_payload()[0].add_related(
        img.read(), 
        maintype='image',  # Tells the email client this part isn't text; it's visual data
        subtype='jpeg',  #Tells it how to decode the pixels.
        cid=image_cid # This is the "handshake." It matches the image data to the ID we put in the HTML <img> tag.
    )

try:
    with smtplib.SMTP(host='smtp.gmail.com', port=587) as smtp:
        smtp.ehlo_or_helo_if_needed()
        smtp.starttls()
        smtp.login(os.getenv('EMAIL_USER'), os.getenv('EMAIL_PASS'))
        smtp.send_message(msg)
        print("Done, my liege! The intel is in your inbox.")
except Exception as e:
    print(f"Transmission failed: {e}")

